name: szakdolgozat_magantaxi_mobil
description: Kiss Máté szakdolgozat mobil oldal.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_lints: ^3.0.1
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  loading_animation_widget: ^1.2.0+4
  dio: ^5.4.0
  cupertino_icons: ^1.0.2
  socket_io_client: ^2.0.3+1
  geolocator: ^11.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_gen:
    integrations:
      flutter_svg: true

flutter:

  assets:
    - lib/assets/images/
    - lib/assets/
    - lib/assets/fonts/

  uses-material-design: true

  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: lib/assets/fonts/JetBrainsMonoRomanRegular.ttf
          weight: 400